services:
  - type: docker
    name: laravel-sqlite-app
    # The build context is the root directory
    dockerContext: .
    plan: free
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://laravel-sqlite-app.onrender.com
      - key: APP_ENV
        value: production