services:
  - type: web
    name: laravel-sqlite-app
    env: php
    plan: free
    buildCommand: "composer install && php artisan key:generate && php artisan storage:link"
    startCommand: "php artisan migrate --force && php artisan serve --host=0.0.0.0"
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://laravel-sqlite-app.onrender.com
      - key: APP_ENV
        value: production
